export const MAILCHIMP_API_URL = process.env.VUE_APP_MAILCHIMP_API_URL
export const MAILCHIMP_USER_ID = process.env.VUE_APP_MAILCHIMP_USER_ID
export const MAILCHIMP_LIST_ID = process.env.VUE_APP_MAILCHIMP_LIST_ID

export default {
  MAILCHIMP_API_URL,
  MAILCHIMP_USER_ID,
  MAILCHIMP_LIST_ID
}
